/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lougw_ffmpeg_FFmpegPlayer */

#ifndef _Included_com_lougw_ffmpeg_FFmpegPlayer
#define _Included_com_lougw_ffmpeg_FFmpegPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lougw_ffmpeg_FFmpegPlayer
 * Method:    playMyMedia
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lougw_ffmpeg_FFmpegPlayer_playMyMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lougw_ffmpeg_FFmpegPlayer
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lougw_ffmpeg_FFmpegPlayer_urlprotocolinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_lougw_ffmpeg_FFmpegPlayer
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lougw_ffmpeg_FFmpegPlayer_avformatinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_lougw_ffmpeg_FFmpegPlayer
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lougw_ffmpeg_FFmpegPlayer_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_lougw_ffmpeg_FFmpegPlayer
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lougw_ffmpeg_FFmpegPlayer_avfilterinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_lougw_ffmpeg_FFmpegPlayer
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lougw_ffmpeg_FFmpegPlayer_configurationinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
